---
apiVersion: v1
kind: Namespace
metadata:
  name: lab-03-config
  labels:
    app.kubernetes.io/name: lab-03-config
    app.kubernetes.io/instance: lab-03
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: kubernetes-labs
    app.kubernetes.io/managed-by: kubectl
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
