---
apiVersion: v1
kind: Service
metadata:
  name: demo-config
  namespace: lab-03-config
  labels:
    app.kubernetes.io/name: demo-config
    app.kubernetes.io/instance: lab-03
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: kubernetes-labs
    app.kubernetes.io/managed-by: kubectl
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: demo-config
    app.kubernetes.io/instance: lab-03
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
